### PR TITLE
Convert the project to use Nix flakes

### PR DESCRIPTION
**Pull request by jiribenes**
_A Flake-based revamp for the whole repo!_ 

## Features

Every released version has:
- a devshell
- a package
- an app
- for all backends

We also support:
- devshells for working on the Effekt compiler

But wait, there's more!
- build-your-own-version functions, for both source-based builds and releases, for all of the backends of your own choice!
- build-your-own-Effekt-package functions, for all of the backends of your choice -- just add a few lines of Nix into your project and see it go!

### CODE REVIEW

**Comment by jiribenes** [comment]
Hey @kap4102, sorry for the ping, but if you're using this project already: is there anything you'd add to the flake? Will this still work with your setup?

**Comment by kap4102** [comment]
Hi, thanks for the ping, this is very helpful to me.
My attempt at packaging effekt as a flake was much less sophisticated than this, i think you managed to implement everything I planned.

Both running effekt and the devshell on x86_64-linux work well for me.

However it looks like the effekt_nightly derivation currently fails to build (an error in the builder for effekt-sbt-dependencies), i will look into this.

**Comment by jiribenes** [comment]
> Hi, thanks for the ping, this is very helpful to me. My attempt at packaging effekt as a flake was much less sophisticated than this, i think you managed to implement everything I planned.

That's great to hear, thanks! :)

> However it looks like the effekt_nightly derivation currently fails to build (an error in the builder for effekt-sbt-dependencies), i will look into this.

Nightly currently fails on a SSH submodule of a non-flake input with: `error: Cannot find Git revision 'ab6aef78fc4ce99a9ad2db8555718d00b03f7b8a' in ref 'main' of repository 'ssh://git@github.com/effekt-lang/kiama.git'! Please make sure that the rev exists on the ref you've specified or add allRefs = true; to fetchGit.`, I still have to think if there's a sane way around it. If not, I'll just merge this without `nightly` and do that part later.

**Comment by jiribenes** [comment]
I tried experimenting with `nightly`, but the problem is that we need to do one compilation as a part of `sbt-derivation`'s `warmup` (otherwise we don't have the dependencies & `sbt update` is not enough). However, during the compilation, we get a **mis**compilation -- the Scala compiler produces a file called `package$?.class`: `Error:  java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: package$?.class`.

**Comment by jiribenes** [comment]
I'm pretty satisfied with the current state, so I'll merge this and make follow-up PRs and/or issues when relevant.

**Pull request merged**
